spring:
  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 80MB
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

controller:
  allow-dangerous-endpoints: false
---

spring:
  profiles: dev-1

controller:
  allow-dangerous-endpoints: true

---

spring:
  profiles: staging

controller:
  allow-dangerous-endpoints: false

---

spring:
  profiles: production

controller:
  allow-dangerous-endpoints: false

---

spring:
  profiles: test, local-dev-h2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

controller:
  allow-dangerous-endpoints: true

---

spring:
  profiles: local-dev-postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/oprah_dev
    driverClassName: org.postgresql.Driver
    username: postgres
    password:

controller:
  allow-dangerous-endpoints: true
